version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.6
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ../01-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../01-mosquitto/users:/mosquitto/config/users
      - ../../ado-tmp-data/mosquitto/data:/mosquitto/data
      - ../../ado-tmp-data/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ../../ado-tmp-data/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:6.3.5
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ../../ado-tmp-data/grafana:/var/lib/grafana
    restart: always


