{
 "title": "Estat sensors",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Sensors",
    "query": "SHOW TAG VALUES FROM messages WITH  KEY = \"name\""
   },
   {
    "name": "Topic",
    "query": "SHOW TAG VALUES WITH KEY = \"channel\""
   },
   {
    "name": "Publisher",
    "query": "SHOW TAG VALUES FROM messages WITH KEY = \"publisher\" WHERE \"devname\" =~ /^$Device$/"
   },
   { "name": "DB", "query": "influxdb" },
   { "name": "time_off_sec", "query": "${VAR_TIME_OFF_SEC}" },
   {
    "name": "Device",
    "label": "Dispositius",
    "query": "SHOW TAG VALUES FROM messages WITH KEY = \"devname\" "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "----\n## Aqüicultura Digital Oberta\n----\n\n\n"
   },
   "content": "----\n## Aqüicultura Digital Oberta\n----\n\n\n"
  },
  { "title": "System heatlh", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "$Sensors",
   "type": "stat",
   "description": "Shows if sensor have been active within the last 120 seconds",
   "gridPos": { "h": 3, "w": 2.4, "x": 0, "y": 4 },
   "repeat": "Sensors",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "messages",
     "query": "SELECT \"value\" FROM \"messages\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) AND time >= now() - 120s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
      { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
     ]
    }
   ]
  },
  {
   "title": "Timeseries data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "repeat": "Sensors",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    },
    {
     "title": "$Sensors",
     "type": "graph",
     "description": "Mostra els valors del sensor en temps",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$Device",
       "measurement": "messages",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
        { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Current sampling rate of $Sensors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "repeat": "Sensors",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "control",
     "query": "SELECT last(\"value\") FROM \"control\" WHERE (\"name\" =~ /^$Sensors$/ AND \"publisher\" =~ /^$Publisher$/) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Sensors$/" },
      { "condition": "AND", "key": "publisher", "operator": "=~", "value": "/^$Publisher$/" }
     ]
    }
   ]
  },
  {
   "title": "Sampling Rate",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 9 },
   "repeat": "Sensors",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}